class CategoryQuote {
  final String categoryTitle;
  final List<String> quotes;

  // Constructor
  CategoryQuote({
    required this.categoryTitle,
    required this.quotes,
  });

  // Static method to get all the quotes by category
  static List<CategoryQuote> getAllCategoryQuotes() {
    return [
      CategoryQuote(
        categoryTitle: 'Life',
        quotes: [
          ' In the middle of every difficulty lies opportunity. – Albert Einstein ',
          ' Life is what happens when you\'re busy making other plans. – John Lennon ',
          ' Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson ',
          ' Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman ',
          ' Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs ',
          ' Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill ',
          ' Happiness is not by chance, but by choice. – Jim Rohn ',
          ' The purpose of our lives is to be happy. – Dalai Lama ',
          ' Life is really simple, but we insist on making it complicated. – Confucius ',
          ' In the end, it’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln ',
          ' Be the change that you wish to see in the world. – Mahatma Gandhi ',
          ' What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson ',
          ' Life isn’t about finding yourself. It’s about creating yourself. – George Bernard Shaw ',
          ' Difficulties in life are intended to make us better, not bitter. – Dan Reeves ',
          ' The best way to predict the future is to invent it. – Alan Kay ',
          ' Life is like riding a bicycle. To keep your balance, you must keep moving. – Albert Einstein ',
          ' Don\'t wait. The time will never be just right. – Napoleon Hill ',
          ' Do what you can, with what you have, where you are. – Theodore Roosevelt ',
          ' Every moment is a fresh beginning. – T.S. Eliot ',
          ' It is not the length of life, but the depth of life. – Ralph Waldo Emerson ',
        ],

      ),
      CategoryQuote(
        categoryTitle: 'Family',
        quotes: [
          ' The love of a family is life’s greatest blessing. ',
          ' Family is not an important thing, it’s everything. – Michael J. Fox ',
          ' In every conceivable manner, the family is link to our past, bridge to our future. – Alex Haley ',
          ' A happy family is but an earlier heaven. – George Bernard Shaw ',
          ' The most important thing in the world is family and love. – John Wooden ',
          ' Rejoice with your family in the beautiful land of life! – Albert Einstein ',
          ' Family means no one gets left behind or forgotten. – David Ogden Stiers ',
          ' The memories we make with our family are everything. – Candace Cameron Bure ',
          ' The strength of a family, like the strength of an army, is in its loyalty to each other. – Mario Puzo ',
          ' Home is where you are loved the most and act the worst. – Marjorie Pay Hinckley ',
          ' Family: like branches on a tree, we all grow in different directions yet our roots remain as one. ',
          ' Being a family means you are a part of something very wonderful. ',
          ' You don’t choose your family. They are God’s gift to you, as you are to them. – Desmond Tutu ',
          ' In time of test, family is best. – Burmese Proverb ',
          ' Call it a clan, call it a network, call it a tribe, call it a family. Whatever you call it, whoever you are, you need one. – Jane Howard ',
          ' Having somewhere to go is home. Having someone to love is family. Having both is a blessing. ',
          ' Other things may change us, but we start and end with family. – Anthony Brandt ',
          ' Families are like fudge – mostly sweet with a few nuts. ',
          ' The family is one of nature’s masterpieces. – George Santayana ',
          ' Blood makes you related, but loyalty makes you family. ',
        ],
      ),
      CategoryQuote(
        categoryTitle: 'Friendship',
        quotes: [
          ' Friendship is born at that moment when one person says to another: “What! You too? I thought I was the only one.” – C.S. Lewis ',
          ' A real friend is one who walks in when the rest of the world walks out. – Walter Winchell ',
          ' Friendship is the only cement that will ever hold the world together. – Woodrow Wilson ',
          ' A friend is someone who knows all about you and still loves you. – Elbert Hubbard ',
          ' True friendship comes when the silence between two people is comfortable. – David Tyson ',
          ' Friendship is the golden thread that ties the heart of all the world. – John Evelyn ',
          ' A single rose can be my garden… a single friend, my world. – Leo Buscaglia ',
          ' Friends are those rare people who ask how we are and then wait to hear the answer. – Ed Cunningham ',
          ' Friendship is not about whom you have known the longest… It’s about who came, and never left your side. ',
          ' A friend is one of the nicest things you can have and one of the best things you can be. ',
          ' There is nothing on this earth more to be prized than true friendship. – Thomas Aquinas ',
          ' Walking with a friend in the dark is better than walking alone in the light. – Helen Keller ',
          ' Friendship is like a rainbow between two hearts. ',
          ' Good friends are like stars. You don’t always see them, but you know they’re always there. ',
          ' A true friend is someone who is there for you when they would rather be anywhere else. – Len Wein ',
          ' A friend is someone who makes it easy to believe in yourself. ',
          ' A friendship that can end never really began. – Publilius Syrus ',
          ' My best friend is the one who brings out the best in me. – Henry Ford ',
          ' Friendship is the only thing in the world concerning the usefulness of which all mankind are agreed. – Cicero ',
          ' Friends are the family we choose for ourselves. ',
        ],

      ),
      CategoryQuote(
        categoryTitle: 'Love',
        quotes: [
          ' Love is composed of a single soul inhabiting two bodies. – Aristotle ',
          ' To love and be loved is to feel the sun from both sides. – David Viscott ',
          ' Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day. ',
          ' You know you’re in love when you can’t fall asleep because reality is finally better than your dreams. – Dr. Seuss ',
          ' Love doesn’t make the world go ‘round. Love is what makes the ride worthwhile. – Franklin P. Jones ',
          ' Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. – Lao Tzu ',
          ' Love is a friendship set to music. – Joseph Campbell ',
          ' Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope. – Maya Angelou ',
          ' The best thing to hold onto in life is each other. – Audrey Hepburn ',
          ' To love oneself is the beginning of a lifelong romance. – Oscar Wilde ',
          ' True love begins when nothing is looked for in return. – Antoine de Saint-Exupéry ',
          ' In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine. – Maya Angelou ',
          ' Love is a canvas furnished by nature and embroidered by imagination. – Voltaire ',
          ' Love is the flower you’ve got to let grow. – John Lennon ',
          ' Where there is love there is life. – Mahatma Gandhi ',
          ' A simple “I love you” means more than money. – Frank Sinatra ',
          ' Love is that condition in which the happiness of another person is essential to your own. – Robert A. Heinlein ',
          ' If I know what love is, it is because of you. – Hermann Hesse ',
          ' Love cures people – both the ones who give it and the ones who receive it. – Karl A. Menninger ',
          ' Love is when the other person’s happiness is more important than your own. – H. Jackson Brown Jr. ',
        ],
      ),
      CategoryQuote(
        categoryTitle: 'Positive',
        quotes: [
          'Keep your face always toward the sunshine—and shadows will fall behind you. —Walt Whitman',
          'Extraordinary things are always hiding in places people never think to look. —Jodi Picoul',
          'Setting goals is the first step in turning the invisible into the visible. —Tony Robbins',
          'You can have it all. Just not all at once. —Oprah Winfrey',
          'I’ve missed more than 9000 shots in my career I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed. —Michael Jordan',
          'Say something positive, and you’ll see something positive. —Jim Thompson',
          'All you need is the plan, the road map, and the courage to press on to your destination. —Earl Nightingale',
          'Train your mind to see the good in every situation. —Unknown',
          'If you can stay positive in a negative situation, you win. —Unknown',
          'Stay positive. Better days are on their way. —Unknown',
          'Only in the darkness can you see the stars. —Martin Luther King, Jr.',
          'I dwell in possibility. —Emily Dickinson',
          'A goal is not always meant to be reached, it often serves simply as something to aim at. – Bruce Lee',
          'A No. 2 pencil and a dream can take you anywhere. —Joyce Meyer',
          'In a gentle way, you can shake the world. —Mahatma Gandhi',
          'Be yourself and people will like you. —Jeff Kinney',
          'Each day provides its own gifts. —Marcus Aurelius',
          'Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you. —Nathaniel Hawthorne',
          'You do not find the happy life. You make it. —Thomas S. Monson',
          'Inspiration comes from within yourself. One has to be positive. When you’re positive, good things happen. —Deep Roy',
          ' Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman ',
          ' Positive anything is better than negative nothing. – Elbert Hubbard ',
          ' Once you replace negative thoughts with positive ones, you’ll start having positive results. – Willie Nelson ',
          ' In order to carry a positive action, we must develop here a positive vision. – Dalai Lama ',
          ' Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. – Helen Keller ',
          ' A positive attitude can really make dreams come true—it did for me. – David Bailey ',
          ' You cannot have a positive life and a negative mind. – Joyce Meyer ',
          ' The only place where your dream becomes impossible is in your own thinking. – Robert H. Schuller ',
          ' Believe you can and you’re halfway there. – Theodore Roosevelt ',
          ' Start each day with a positive thought and a grateful heart. – Roy T. Bennett ',
          ' Happiness is an attitude. We either make ourselves miserable, or happy and strong. The amount of work is the same. – Francesca Reigler ',
          ' Yesterday is not ours to recover, but tomorrow is ours to win or lose. – Lyndon B. Johnson ',
          ' Perpetual optimism is a force multiplier. – Colin Powell ',
          ' Act as if what you do makes a difference. It does. – William James ',
          ' Don’t let yesterday take up too much of today. – Will Rogers ',
          ' Every day may not be good, but there’s something good in every day. – Alice Morse Earle ',
          ' The more you praise and celebrate your life, the more there is in life to celebrate. – Oprah Winfrey ',
          ' Attitude is a little thing that makes a big difference. – Winston Churchill ',
          ' It makes a big difference in your life when you stay positive. – Ellen DeGeneres ',
          ' Surround yourself with positive people who will support you when it rains, not just when it shines. – Unknown ',
        ],

      ),CategoryQuote(
        categoryTitle: 'Inspiration',
        quotes: [
          'It takes courage to grow up and become who you really are. — E.E. Cummings',
          'Your self-worth is determined by you. You don’t have to depend on someone telling you who you are. — Beyoncé',
          'Nothing is impossible. The word itself says I’m possible!’ — Audrey Hepburn',
          'Keep your face always toward the sunshine, and shadows will fall behind you. — Walt Whitman',
          'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You’re on your own. And you know what you know. And you are the guy who’ll decide where to go. — Dr. Seuss',
          'Attitude is a little thing that makes a big difference. — Winston Churchill',
          'To bring about change, you must not be afraid to take the first step. We will fail when we fail to try. — Rosa Parks',
          'All our dreams can come true, if we have the courage to pursue them. — Walt Disney',
          'Don’t sit down and wait for the opportunities to come. Get up and make them. — Madam C.J. Walker',
          'Champions keep playing until they get it right. — Billie Jean King',
          'I am lucky that whatever fear I have inside me, my desire to win is always stronger. — Serena Williams',
          'You are never too old to set another goal or to dream a new dream. — C.S. Lewis',
          'It is during our darkest moments that we must focus to see the light. — Aristotle',
          'Believe you can and you’re halfway there. — Theodore Roosevelt',
          'Life shrinks or expands in proportion to one’s courage. — Anaïs Nin',
          'Just don’t give up trying to do what you really want to do. Where there is love and inspiration, I don’t think you can go wrong. — Ella Fitzgerald',
          'Try to be a rainbow in someone’s cloud. — Maya Angelou',
          'If you don’t like the road you’re walking, start paving another one. — Dolly Parton',
          'Real change, enduring change, happens one step at a time. — Ruth Bader Ginsburg',
          'All dreams are within reach. All you have to do is keep moving towards them. — Viola Davis',
          'It is never too late to be what you might have been. — George Eliot',
          'When you put love out in the world it travels, and it can touch people and reach people in ways that we never even expected. — Laverne Cox',
          'Give light and people will find the way. — Ella Baker',
          'It always seems impossible until it’s done. — Nelson Mandela',
          'Don’t count the days, make the days count. — Muhammad Ali',
          'If you risk nothing, then you risk everything. — Geena Davis',
          'Definitions belong to the definers, not the defined. — Toni Morrison',
          'When you have a dream, you’ve got to grab it and never let go. — Carol Burnett',
          'Never allow a person to tell you no who doesn’t have the power to say yes. — Eleanor Roosevelt',
          'When it comes to luck, you make your own. — Bruce Springsteen',
          'If you’re having fun, that’s when the best memories are built. — Simone Biles',
          'Failure is the condiment that gives success its flavor. — Truman Capote',
          'Hard things will happen to us. We will recover. We will learn from it. We will grow more resilient because of it. — Taylor Swift',
          'Your story is what you have, what you will always have. It is something to own. — Michelle Obama',
          'To live is the rarest thing in the world. Most people just exist. — Oscar Wilde',
          'You define beauty yourself, society doesn’t define your beauty. — Lady Gaga',
          'Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you. — Mary Lou Retton',
          'You just gotta keep going and fighting for everything, and one day you’ll get to where you want. — Naomi Osaka',
          'If you prioritize yourself, you are going to save yourself. — Gabrielle Union',
          'No matter how far away from yourself you may have strayed, there is always a path back. You already know who you are and how to fulfill your destiny. — Oprah Winfrey',
          'A problem is a chance for you to do your best. — Duke Ellington',
          'You can’t turn back the clock. But you can wind it up again. — Bonnie Prudden',
          'When you can’t find someone to follow, you have to find a way to lead by example. — Roxane Gay',
          'There is no better compass than compassion. — Amanda Gorman',
          'Stand before the people you fear and speak your mind – even if your voice shakes. — Maggie Kuhn',
          'It’s a toxic desire to try to be perfect. I realized later in life that the challenge is not to be perfect. It’s to be whole. — Jane Fonda',
          'Vitality shows not only in the ability to persist but in the ability to start over. — F. Scott Fitzgerald',
          'The most common way people give up their power is by thinking they don’t have any. — Alice Walker',
          'Love yourself first and everything else falls into line. — Lucille Ball',
          'In three words I can sum up everything I’ve learned about life: It goes on. — Robert Frost',
          ' The best way to predict the future is to create it. – Peter Drucker ',
          ' Do what you can, with what you have, where you are. – Theodore Roosevelt ',
          ' Everything you’ve ever wanted is on the other side of fear. – George Addair ',
          ' Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill ',
          ' Believe you can and you’re halfway there. – Theodore Roosevelt ',
          ' Your time is limited, don’t waste it living someone else’s life. – Steve Jobs ',
          ' If you want to achieve greatness stop asking for permission. – Anonymous ',
          ' Dream big and dare to fail. – Norman Vaughan ',
          ' It always seems impossible until it’s done. – Nelson Mandela ',
          ' Don’t watch the clock; do what it does. Keep going. – Sam Levenson ',
          ' The harder you work for something, the greater you’ll feel when you achieve it. – Anonymous ',
          ' You are never too old to set another goal or to dream a new dream. – C.S. Lewis ',
          ' Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis ',
          ' Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau ',
          ' Start where you are. Use what you have. Do what you can. – Arthur Ashe ',
          ' The way to get started is to quit talking and begin doing. – Walt Disney ',
          ' Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt ',
          ' Act as if what you do makes a difference. It does. – William James ',
          ' Don’t let what you cannot do interfere with what you can do. – John Wooden ',
          ' The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt ',
        ],
      ),
      CategoryQuote(
        categoryTitle: 'Success',
        quotes: [
          ' Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. – Albert Schweitzer ',
          ' Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau ',
          ' Don’t be afraid to give up the good to go for the great. – John D. Rockefeller ',
          ' The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr. ',
          ' Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill ',
          ' Opportunities don’t happen. You create them. – Chris Grosser ',
          ' Don’t let the fear of losing be greater than the excitement of winning. – Robert Kiyosaki ',
          ' I find that the harder I work, the more luck I seem to have. – Thomas Jefferson ',
          ' The road to success and the road to failure are almost exactly the same. – Colin R. Davis ',
          ' Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett ',
          ' Success is getting what you want. Happiness is wanting what you get. – Dale Carnegie ',
          ' In order to succeed, your desire for success should be greater than your fear of failure. – Bill Cosby ',
          ' Action is the foundational key to all success. – Pablo Picasso ',
          ' Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit. – Conrad Hilton ',
          ' Success is how high you bounce when you hit bottom. – George S. Patton ',
          ' The successful warrior is the average man, with laser-like focus. – Bruce Lee ',
          ' Try not to become a man of success. Rather become a man of value. – Albert Einstein ',
          ' I never dreamed about success. I worked for it. – Estee Lauder ',
          ' Some people dream of success, while others wake up and work hard at it. – Napoleon Hill ',
          ' Success is not in what you have, but who you are. – Bo Bennett ',
        ],
      ),
      CategoryQuote(
        categoryTitle: 'Happiness',
        quotes: [
          ' Happiness is not something ready made. It comes from your own actions. – Dalai Lama ',
          ' The purpose of our lives is to be happy. – Dalai Lama ',
          ' Happiness depends upon ourselves. – Aristotle ',
          ' For every minute you are angry, you lose sixty seconds of happiness. – Ralph Waldo Emerson ',
          ' Happiness is not a goal; it is a by-product. – Eleanor Roosevelt ',
          ' Happiness is a state of mind. It’s just according to the way you look at things. – Walt Disney ',
          ' Most folks are as happy as they make up their minds to be. – Abraham Lincoln ',
          ' Happiness is the secret to all beauty. There is no beauty without happiness. – Christian Dior ',
          ' Happiness is not out there, it’s in you. – Unknown ',
          ' The happiest people don’t have the best of everything; they make the best of everything. – Unknown ',
          ' Be happy for this moment. This moment is your life. – Omar Khayyam ',
          ' True happiness arises, in the first place, from the enjoyment of oneself. – Joseph Addison ',
          ' Happiness is only real when shared. – Christopher McCandless ',
          ' Success is getting what you want, happiness is wanting what you get. – W.P. Kinsella ',
          ' Happiness radiates like the fragrance from a flower and draws all good things toward you. – Maharishi Mahesh Yogi ',
          ' If you want to be happy, be. – Leo Tolstoy ',
          ' Happiness is not having what you want. It is appreciating what you have. – Unknown ',
          ' It is not how much we have, but how much we enjoy, that makes happiness. – Charles Spurgeon ',
          ' Happiness is when what you think, what you say, and what you do are in harmony. – Mahatma Gandhi ',
          ' There is only one happiness in this life, to love and be loved. – George Sand ',
        ],

      ),CategoryQuote(
        categoryTitle: 'Famous',
        quotes: [
          ' The only way to do great work is to love what you do. – Steve Jobs ',
          ' In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr. ',
          ' It is never too late to be what you might have been. – George Eliot ',
          ' Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll ',
          ' To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson ',
          ' Don’t count the days, make the days count. – Muhammad Ali ',
          ' You must be the change you wish to see in the world. – Mahatma Gandhi ',
          ' The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb ',
          ' You miss 100% of the shots you don’t take. – Wayne Gretzky ',
          ' Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw ',
          ' The journey of a thousand miles begins with one step. – Lao Tzu ',
          ' If you want to go fast, go alone. If you want to go far, go together. – African Proverb ',
          ' Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill ',
          ' The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt ',
          ' Believe you can and you’re halfway there. – Theodore Roosevelt ',
          ' Life is really simple, but we insist on making it complicated. – Confucius ',
          ' It does not matter how slowly you go as long as you do not stop. – Confucius ',
          ' Happiness can be found, even in the darkest of times, if one only remembers to turn on the light. – J.K. Rowling ',
          ' The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt ',
          ' You only live once, but if you do it right, once is enough. – Mae West ',
        ],
      ),
      CategoryQuote(
        categoryTitle: 'Wisdom',
        quotes: [
          ' Wisdom begins in wonder. – Socrates ',
          ' The only true wisdom is in knowing you know nothing. – Socrates ',
          ' Knowledge speaks, but wisdom listens. – Jimi Hendrix ',
          ' Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. – Buddha ',
          ' A fool thinks himself to be wise, but a wise man knows himself to be a fool. – William Shakespeare ',
          ' The unexamined life is not worth living. – Socrates ',
          ' It is not length of life, but depth of life. – Ralph Waldo Emerson ',
          ' The wise man does at once what the fool does finally. – Niccolò Machiavelli ',
          ' Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power. – Lao Tzu ',
          ' A wise person does not need to be told what to do; they are capable of discerning the right course themselves. – Confucius ',
          ' The only source of knowledge is experience. – Albert Einstein ',
          ' Silence is a source of great strength. – Lao Tzu ',
          ' There is no remedy for love but to love more. – Henry David Thoreau ',
          ' Wisdom is not a product of schooling but of the lifelong attempt to acquire it. – Albert Einstein ',
          ' Time, the devourer of all things, is also the best teacher. – Plato ',
          ' A person who never made a mistake never tried anything new. – Albert Einstein ',
          ' In the middle of difficulty lies opportunity. – Albert Einstein ',
          ' To know, is to know that you know nothing. That is the meaning of true knowledge. – Confucius ',
          ' The more I read, the more I acquire, the more certain I am that I know nothing. – Voltaire ',
          ' Wisdom is the reward you get for a lifetime of listening when you’d rather talk. – Mark Twain ',
        ],
      ),
    ];
  }
}
